[default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 200
remappings = ["hardhat/=node_modules/hardhat/","@openzeppelin/=node_modules/@openzeppelin/","hardhat-deploy/=node_modules/hardhat-deploy/", "@uniswap/=node_modules/@uniswap/"]
verbosity = 1
src = "./contracts/"
out = ".dapp"
gas_reports = ['*']
# export DAPP_SOLC_VERSION=0.8.9
